name: Run Tests on Staging Branch

on:
  push:
    branches:
      - staging

jobs:
  run-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend-server

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install pip
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest